name: Test Workflow
on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
    contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Restore result cache"
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: README.md
          key: "result-cache-v1-${{ github.run_id }}"
          restore-keys: |
            result-cache-v1-

      - run: "cat README.md"
      - run: "echo blabla >> README.md"

      - name: "Save result cache"
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: README.md
          key: "result-cache-v1-${{ github.run_id }}"
